package:
  name: relics
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - VERSION
    - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - bw2io
    - bw2data

test:
  imports:
    - relics

about:
  home: https://github.com/romainsacchi/relics
  license: BSD License
  summary: "Adds indicators to assess resource extraction associated to the life-cycle of a product system."
license_family: BSD